language: python

python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"

env:
  - AWS_DEFAULT_REGION=xxxx

install:
  - pip install codecov coverage
  - pip install -r requirements.txt

script:
  - coverage run tests.py

after_success:
  - codecov
