language: python
cache: pip

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"

env:
  - AWS_DEFAULT_REGION=us-east-1 AWS_ACCESS_KEY_ID=xxxx AWS_SECRET_ACCESS_KEY=xxxx

before_install:
  # https://github.com/travis-ci/travis-ci/issues/7940#issuecomment-311411559
  - export BOTO_CONFIG=/dev/null

install:
  - pip install codecov coverage
  - pip install -r requirements.txt

script:
  - coverage run tests.py

after_success:
  - codecov
